name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  workflow_dispatch:

permissions:
  contents: write

env: 
  NEEDS_DEPLOY: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Needs deploy echo
        run:
          echo ${{ env.NEEDS_DEPLOY }}
      - uses: actions/setup-node@v4
        with:
          node-version: '25'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
      - name: Trigger deployment
        if: ${{ env.NEEDS_DEPLOY == 'true'}}
        run: curl https://api.render.com/deploy/srv-${{secrets.RENDER_SERVICE_ID}}?key=${{secrets.RENDER_SERVICE_KEY}} 
      - name: Check Secret Access
        run: |
          if [ -z "${{ secrets.DISCORD_WEBHOOK }}" ]; then
            echo "SECRET IS EMPTY!"
          else
            echo "Secret is found (length: ${#SECRET})"
          fi
        env:
          SECRET: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Build Success
        uses: rjstone/discord-webhook-notify@v2
        if: success() && github.event_name == 'push'
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          title: Build Success
          severity: info
          details: Build successful.
      - name: Build Failure
        uses: rjstone/discord-webhook-notify@v2
        if: failure() && github.event_name == 'push'
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: error
          color: '#ff00aa'
          title: Build Failed
          description: |
            **Repository:** ${{ github.repository }}
            **Branch:** ${{ github.ref_name }}
            **Event:** ${{ github.event_name }}
          details: |
            **Author:** ${{ github.actor }}
            **Commit:** ${{ github.event.head_commit.message }}

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch